# Generated by Django 3.2.18 on 2023-05-09 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category_type',
            field=models.CharField(choices=[('food', 'Food'), ('drink', 'Drink'), ('toys', 'Toys'), ('technology', 'Technology'), ('sports', 'Sports'), ('clothing', 'Clothing'), ('footwear', 'Footwear'), ('household', 'Household'), ('homeware', 'Homeware'), ('jewellery', 'Jewellery'), ('diy', 'DIY'), ('accessories', 'Accessories'), ('other', 'Other')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image_filter',
            field=models.CharField(default='normal', max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
